//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APHATT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM
    {
        public int ADMID { get; set; }
        public string ADMAccount { get; set; }
        public string pass { get; set; }
    }
}
