//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APHATT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.TrainerTopics = new HashSet<TrainerTopic>();
        }
    
        public int TrainerID { get; set; }
        public string TrainerExternal { get; set; }
        public string TrainerInternalType { get; set; }
        public string TrainerWorkingPlace { get; set; }
        public string TrainerTelephone { get; set; }
        public string TrainerRmail { get; set; }
        public string TrainerAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerTopic> TrainerTopics { get; set; }
    }
}
