//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APHATT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerTopic
    {
        public int TrainerTopicID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<System.DateTime> TrainerTopicDate { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
