//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APHATT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int TraineeID { get; set; }
        public string TraineeName { get; set; }
        public string TraineeAccounts { get; set; }
        public string TraineeAge { get; set; }
        public string TraineeDateOfBirth { get; set; }
        public string TraineeEducation { get; set; }
        public string TraineeMainProgrammingLanguage { get; set; }
        public string TraineeTOEIC { get; set; }
        public string TraineeExperienceDetails { get; set; }
        public string TraineeDepartment { get; set; }
        public string TraineeLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
